apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-baseline
  labels:
    app: sampleapp
    version: baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
      version: baseline
  template:
    metadata:
      labels:
        app: sampleapp
        version: baseline
    spec:
      containers:
        - name: app1-nginx
          image: agilesolutions/app1nginx
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: my-acr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-canary
  labels:
    app: sampleapp
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
      version: canary
  template:
    metadata:
      labels:
        app: sampleapp
        version: canary
    spec:
      containers:
        - name: app1-nginx
          image: agilesolutions/app1nginx
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: my-acr-secret
