trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: azure-pipelines-canary-k8s # name of ACR image
  dockerRegistryServiceConnection: 'dockerhub' # name of ACR service connection
  imageRepository: 'agilesolutions/azure-pipelines-canary-k8s' # name of image repository
  containerRegistry: 'Docker Hub' # name of Azure container registry
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: app/Dockerfile
        tags: |
          $(tag)

    - publish: manifests
      artifact: manifests

    - publish: misc
      artifact: misc
- stage: DeployCanary
  displayName: Deploy canary
  dependsOn: Build
  condition: succeeded()


  jobs:
  - deployment: Deploycanary
    displayName: Deploy canary
    pool:
      vmImage: ubuntu-latest
    environment: 'akscanary'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@1
            displayName: Create Docker Registry Secret
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'azure-pipelines-canary-sc'
              azureResourceGroup: 'aks-cluster-template_rg001'
              kubernetesCluster: 'aks101cluster'
              secretType: 'dockerRegistry'
              secretName: 'my-acr-secret'
              dockerRegistryEndpoint: 'azure-pipelines-canary-acr'

          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'azure-pipelines-canary-sc'
              azureResourceGroup: 'aks-cluster-template_rg001'
              kubernetesCluster: 'aks101cluster'
              strategy: 'canary'
              percentage: '25'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              imagePullSecrets: 'my-acr-secret'

          - task: KubernetesManifest@1
            displayName: Deploy Forbio to Kubernetes cluster
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'azure-pipelines-canary-sc'
              azureResourceGroup: 'aks-cluster-template_rg001'
              kubernetesCluster: 'aks101cluster'
              manifests: '$(Pipeline.Workspace)/misc/*'